### ISSUE TITLE
cassandra in unhealthy state in dcos even if cluster is fine

### ISSUE THREAD

**Issue by kevinschmidt** [mesosphere/cassandra-mesos#105]
steps to reproduce from clean state in standard aws cluster (5 slaves).

1. dcos install cassandra
2. wait for healthy state
3. terminate 1 EC instance that has a Cassandra executor running
4. wait for auto-scaling to spin up another instance to replace the terminate one
5. call POST /node/{terminated node}/terminate/
6. wait for Cassandra to spin up another executor to get back to 3

After this we have an essential health cluster with an unreachable node. No follow up REST call will remove the terminated node from the cluster and bring the cluster back into healthy state in dcos. Calls tried are node/{}/make-non-seed, node/{}/replace, /repair/start (repair is hanging).
Removing the node with nodetool noderemove also doesn't change the status from unhealthy in dcos even if the underlying Cassandra cluster is in perfect health.

cluster health report: https://gist.github.com/kevinschmidt/352e2a3a9c056699fa44
output of nodetool: https://gist.github.com/kevinschmidt/17b50760963199a5e005

**Comment by snazy** [comment]
The "node object" is actually only removed during a resource-offer for that node (which did/can never arrive). FTR: it is correct that the node-object is not removed - the actual failure could have been anything from a network hiccup to a fatal server failure (the node can technically reappear).

The node object is removed when the first health check arrives for the replacement node.

To be clear, the procedure to cleanly replace a failed EC instance must be:
1. Terminate the node via the REST call (so basically make it eligible for replacement)
2. Wait until the CassandraScheduler recognizes that the node has no active tasks/executors
3. Let auto-scale start a new node to replace the failed one. Do NOT let auto-scale just scale-up without replacement. This could be the reported "issue" - the node's just been added - not replaced.

FTR: feels that a REST management method to forcibly remove a node is missing.
