### ISSUE TITLE
Build Fails with mesosphere.mesos.util.* not found

### ISSUE THREAD

**Issue by tnn1t1s** [mesosphere/cassandra-mesos#11]
Running build.sh from head, I get the following failure (Mac OS 10.9.3)

[ERROR] /Users/xxx/Developer/cassandra/cassandra-mesos/src/main/scala/mesosphere/cassandra/CassandraScheduler.scala:4: error: object ScalarResource is not a member of package mesosphere.mesos.util
[ERROR] import mesosphere.mesos.util.ScalarResource
[ERROR]        ^
[ERROR] /Users/xxx/Developer/cassandra/cassandra-mesos/src/main/scala/mesosphere/cassandra/Logger.scala:3: error: object log4j is not a member of package org.apache
[ERROR] import org.apache.log4j.{Priority, Level, Logger}
[ERROR]                   ^
[ERROR] /Users/xxx/Developer/cassandra/cassandra-mesos/src/main/scala/mesosphere/cassandra/Logger.scala:12: error: not found: value Logger
[ERROR]   lazy val logger = Logger.getLogger(getClass)
[ERROR]                     ^
[ERROR] /Users/xxx/Developer/cassandra/cassandra-mesos/src/main/scala/mesosphere/cassandra/CassandraScheduler.scala:138: error: not found: value ScalarResource
[ERROR]       case (k, v) => ScalarResource(k, v).toProto
[ERROR]                      ^

**Comment by BenWhitehead** [comment]
Obsolete framework has been rewritten.
