### ISSUE TITLE
Cassandra log file missing on cassandra-mesos-2.1.2-1

### ISSUE THREAD

**Issue by tanpinsiang** [mesosphere/cassandra-mesos#13]
Cassandra-mesos-2.1.2 build from master are working great, except the is no log file form Cassandra. Cassandra will emit the warning below. 

    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/tmp/mesos/slaves/20141216-201216-1694607552-5050-3917-S4/frameworks/20141216-215902-1694607552-5050-6890-0000/executors/cassandra.58031e09-460a-4df6-8ff2-fbcf7a1da6bd/runs/17479497-99fb-432a-a947-77702c8200e8/cassandra-mesos-2.1.2-1/lib/cassandra-mesos-2.1.2-1-deps.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/tmp/mesos/slaves/20141216-201216-1694607552-5050-3917-S4/frameworks/20141216-215902-1694607552-5050-6890-0000/executors/cassandra.58031e09-460a-4df6-8ff2-fbcf7a1da6bd/runs/17479497-99fb-432a-a947-77702c8200e8/cassandra-mesos-2.1.2-1/lib/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
    log4j:WARN No appenders could be found for logger     (org.apache.cassandra.service.CassandraDaemon).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

After deleting cassandra-mesos-2.1.2-1-deps.jar, cassandra binary works well and does emit log. However this will cause problem for cassandra-mesos.
Cassandra-mesos-2.0.5 does not have the same problem.

Thankyou
Wish everyone merry Christmas!

**Comment by BenWhitehead** [comment]
Obsolete framework has been rewritten.
