### ISSUE TITLE
Mesos roles

### ISSUE THREAD

**Issue by AndriiOmelianenko** [mesosphere/cassandra-mesos#139]
Hi guys,

I'm just checking if Mesos roles will be implemented, so the scheduler and executors can accept different roles.

**Comment by BenWhitehead** [comment]
Roles are already implemented, and can be configured by setting the `CASSANDRA_FRAMEWORK_MESOS_ROLE` environment variable when starting the framework.  This will cause the framework to register with mesos using the specified role and will receive offers for that role.

If you are running dcos, this can be set in options.json:
```json
{
  "cassandra": {
    "framework": {
      "role": "cassandra-role"
    }
  }
}
```

And at install time do `docs package install cassandra --options=options.json`

Please note that configuration can not be changed after the framework has been initialized, so this needs to be done at install time.

**Comment by keithchambers** [comment]
Thank you for the question!
