### ISSUE TITLE
how to stop / restart cassandra-mesos

### ISSUE THREAD

**Issue by xasima** [mesosphere/cassandra-mesos#14]
We may use multiple-ssh (http://grokbase.com/t/cassandra/user/117ncdcha7/how-to-stop-the-whole-cluster-start-the-whole-cluster-like-in-hadoop-hbase) or direct container manipulation (https://github.com/jimenezrick/docker-cassandra-cluster/blob/master/scripts/run-cassandra-cluster)  to issue  stop/restart command for  cassandra instances on several nodes in cluster.

It seems that the kill of cassandra-mesos processe doesn't update appropriate notice in zookeeper tree, so it's needed to update the tree manually (zk command line or exhibitor UI editor) to completely clean up the state.

It seems that some basic commands on zk tree to delete latest cassandra-mesos data (on cassandra-mesos stop)  may be  introduce.

**Comment by BenWhitehead** [comment]
Obsolete framework has been rewritten.
