### ISSUE TITLE
Debugging Cassandra startup

### ISSUE THREAD

**Issue by khaverlo** [mesosphere/cassandra-mesos#143]
I'm going through bringup with Cassandra-Mesos and while I see the framework displayed in Mesos UI and can access the REST APIs, I don't see any indication in the logs that Cassandra has started or was attempting to start.  The logs I am looking in are those in the sandbox for cassandra-mesos.log, stderr, and stdout.  Trying to figure out how best to debug Cassandra not starting.

**Comment by BenWhitehead** [comment]
@khaverlo The first place to check is the cluster health report.

`GET /health/cluster/report`[1] will return a json document outlining several things that are evaluated for health.

Second, in cassandra-mesos.log look for log lines containing "Insufficient resources" to get an explanation as to why resources are being declined.

[1] http://mesosphere.github.io/cassandra-mesos/docs/rest-api.html#get-health-cluster-report

**Comment by khaverlo** [comment]
Investigating this further and the issue for me was that the scheduler would register with mesos which in turn would send an acknowledgement to the slave node.  The slave node would never receive the acknowledgement and would again attempt to register.  Mesos uses a random port range between 30000-60000 to communicate back to the slave node.  I opened those port ranges and the scheduler was able to successfully register.  The comments you had in:  https://github.com/mesosphere/cassandra-mesos/issues/144  was helpful in understanding the situation.
