### ISSUE TITLE
Failed to allocate tasks on DigitalOcean, and more

### ISSUE THREAD

**Issue by pcj** [mesosphere/cassandra-mesos#17]
Several issues:

1. Upon spinning up a test cluster in digital ocean environment and installing cassandra-mesos as described...

```
# Downloaded and unpacked archive
$ tar xzf cassandra-mesos-*.tgz

# Updated configuration
$ vi conf/mesos.yaml # updated mesos.master.url with mesos-master IP

# Register framework
# bin/cassandra-mesos 
```

... Task allocation failed due to mesos attempting to access unknown host; wget failed.

```
--2015-01-21 23:54:37--  http://development-3657-d15:8282/cassandra.yaml
Resolving development-3657-d15 (development-3657-d15)... failed: Name or service not known.
wget: unable to resolve host address `development-3657-d15'
```

Checking `/etc/hosts` on the slave contains no entry for mesos-master `development-3657-d15`, so wget failed.  I was able to rescue this by explicitly providing the mesos-master ip address to undocument configuration variable in `mesos.yaml`: `cassandra.confServer.hostname`:

```
mesos.master.url: 'zk://104.131.15.45:2181/mesos'
state.zk: '104.131.15.45:2181'
cassandra.confServer.hostname: 104.131.15.45
```

However, this seems like a brittle solution as I would expect it to fail if a new master is elected.  Did I miss something here?  Should my DO cluster slaves have an entry for the master in /etc/hosts?

**Comment by pcj** [comment]
Got it working by configuring `cassandra.yaml:listen_address` to the public ip of the slave where cassandra task was deployed.

**Comment by BenWhitehead** [comment]
Obsolete framework has been rewritten.
