### ISSUE TITLE
Suggested URI for a 2.1.5 or newer version of cassandra?

### ISSUE THREAD

**Issue by johnweldon** [mesosphere/cassandra-mesos#171]
2.1.5 fixed a bug ([CASSANDRA-9216](https://issues.apache.org/jira/browse/CASSANDRA-9216)) that is causing some of our tables to not get compacted.

The [currently suggested link](https://downloads.mesosphere.io/cassandra-mesos/artifacts/0.2.1-SNAPSHOT-608-master-d1c2cf30c8/cassandra-mesos-0.2.1-SNAPSHOT-608-master-d1c2cf30c8.tar.gz) in the marathon.json template is for 2.1.4 

Can you suggest a download link for 2.1.5 or newer?

**Comment by ad1ous** [comment]
You will most likely need to build the framework yourself and host somewhere accessible to your mesos cluster - there are forks of this project that have updated the version of cassandra in use.

**Comment by johnweldon** [comment]
Thank you.

John Weldon
