### ISSUE TITLE
Cassandra tasks are not restarted when the Mesos cluster is shutdown

### ISSUE THREAD

**Issue by singularity-sg** [mesosphere/cassandra-mesos#6]
The cassandra-mesos tasks were able to run when the framework is first introduced with a cassandra clustername. However, whenever I restart the mesos cluster, the Cassandra-mesos tasks do not re-run even when the cassandra-mesos scheduler receives sufficient resource offers from the slave mesos nodes. 

An example of the output from the mesos nodes is :

445421 [Thread-85] INFO mesosphere.cassandra.CassandraScheduler  - Got new resource offers ArrayBuffer(ip-10-153-171-197.ec2.internal, ip-10-144-185-186.ec2.internal, ip-10-187-28-30.ec2.internal, ip-10-146-199-114.ec2.internal)
445438 [Thread-85] INFO mesosphere.cassandra.CassandraScheduler  - resources offered: List((cpus,2.0), (mem,6493.0), (disk,95545.0), (ports,0.0))
445438 [Thread-85] INFO mesosphere.cassandra.CassandraScheduler  - resources required: List((cpus,0.3), (mem,2048.0), (disk,40000.0))
445441 [Thread-85] INFO mesosphere.cassandra.CassandraScheduler  - resources offered: List((cpus,2.0), (mem,6493.0), (disk,95545.0), (ports,0.0))

Note to self : Will need to examine the Scheduler criteria for acceptance to understand why it is not accepting the offers.

**Comment by Bleakwise** [comment]
I have this same issue, been driving me mad. Where is the cassandraMesos directory?

**Comment by Bleakwise** [comment]
UPDATE2:
Using the zkCli.sh utility I went into ZK and deleted
/cassandraMesos/tesserver/app:nodeSet and app:frameworkId which also got cassandra-mesos back running.

I'm going to sleep, but tomorrow I plan to see if just deleting app:nodeset OR just app:frameworkId gets it going as well. Once either the nodeset or frameworkid has been isolated I'll better know how to continue in some resolution.

**Comment by BenWhitehead** [comment]
Obsolete framework has been rewritten.
