### ISSUE TITLE
could not connect to the scheduler host and port using cqlsh

### ISSUE THREAD

**Issue by yanglei99** [mesosphere/cassandra-mesos#74]
cqlsh can connect to the live node and port, but not the scheduler 's host and port. 

cqlsh <my scheduler host> <my scheduler port>
Connection error: ('Unable to connect to any servers', {'<my scheduler host>': OperationTimedOut('errors=Timed out creating connection, last_host=None',)})

Thanks. Yang

**Comment by BenWhitehead** [comment]
The scheduler does not provide an interface for cqlsh itself.

Though you can use the `com-cqlsh` script that is in the repo to try and connect. (what this script does is it connects to the framework gets the the arg set for cqlsh the hosts and port).

If you run into issues using `com-cqlsh` let us know and we can try to help.
