### ISSUE TITLE
It is possible for the cassandra framework to get into a state where there are nodes but no tasks.

### ISSUE THREAD

**Issue by BenWhitehead** [mesosphere/cassandra-mesos#97]
See [gist](https://gist.github.com/lucamartinetti/38f8e13920739d6b22d6) from @lucamartinetti

**Comment by BenWhitehead** [comment]
HI @lucamartinetti I'm creating a new build right now it additional logging in the code that is evaluating the resource offer from mesos.

Can you please try restarting the framework with this new [marathon.json](https://teamcity.mesosphere.io/guestAuth/repository/download/Oss_Mesos_Cassandra_CassandraFramework/15606:id/marathon.json).  This should pull the new scheduler code and give us a little better logging.

**Comment by lucamartinetti** [comment]
Trying now

**Comment by lucamartinetti** [comment]
@BenWhitehead do you want to chat on skype? please add me "lucamartinetti"

**Comment by lucamartinetti** [comment]
I have it running. Had to delete some previous zookeeper data. I can give you more details if needed

**Comment by BenWhitehead** [comment]
@lucamartinetti I'm glad it's working now, thanks for testing.  Any extra details would be great so that I can try and make sure this doesn't happen again.
